In [55]:
#refereence implementation of davidson algorithm
#https://joshuagoings.com/2013/08/23/davidsons-method/

In [56]:
import numpy as np
import time

In [64]:
n = 1000

In [65]:
sparsity = 0.000001
A = np.zeros((n,n))
for i in range(n):
    A[i,i] = i + 1
A = A + sparsity*np.random.randn(n,n)
A = (A.T + A)/2

In [66]:
A[0,0]

0.9999995984881729

In [86]:
tol = 1E-10

In [87]:
k = 4
eig = 2
t = np.eye(n,k)
V = np.zeros((n,n))
I = np.eye(n)

In [88]:
np.eye(4,1)

array([[1.],
       [0.],
       [0.],
       [0.]])

In [89]:
kmax = 40

In [99]:
ts = []
for i in range(21):
    V = np.zeros((n,n))
    t1 = time.time()
    for m in range(k,kmax,k):
       # print(m)
        if m <= k:
            for j in range(0,k):
                V[:,j] = t[:,j]/np.linalg.norm(t[:,j])
            theta_old = 1
        else:
            theta_old = theta[:eig]
        V,R = np.linalg.qr(V) #ensures vectors are orthonormal
        T = np.dot(V[:,:(m+1)].T, np.dot(A,V[:,:(m+1)])) #T is the projection of A onto the space spanned by V
       # print(T)
        THETA,S = np.linalg.eig(T)
       # print(THETA)
        idx = THETA.argsort()
        theta = THETA[idx] #sorted THETA
        s = S[:,idx] #sorted S
        for j in range(k):
            w = np.dot((A - theta[j]*I), np.dot(V[:,:(m+1)],s[:,j])) #if theta was exact eigenvalue, w -> 0
            q = w/(theta[j] - A[j,j]) #scaling by 1/(approx eig j - diag element j)
           # print(w)
            V[:,(m+j+1)] = q #add scaled q to trial vectors
        norm = np.linalg.norm(theta[:eig] - theta_old)
        if norm < tol:
            print( theta[:2] )
            break
    ts.append(time.time() - t1)

[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]
[0.9999996  2.00000143]


In [102]:
ts

[0.23541569709777832,
 0.17555952072143555,
 0.20595693588256836,
 0.1842048168182373,
 0.20061230659484863,
 0.18400001525878906,
 0.1994473934173584,
 0.1623239517211914,
 0.18283939361572266,
 0.18391132354736328,
 0.2164444923400879,
 0.17099690437316895,
 0.20885753631591797,
 0.18445873260498047,
 0.21234655380249023,
 0.1876523494720459,
 0.2160043716430664,
 0.18795251846313477,
 0.2087085247039795,
 0.17346954345703125,
 0.19208097457885742]

In [101]:
np.mean(ts)

0.1939639931633359

In [48]:
X = np.triu(A)

In [51]:
X[:,2]

array([-2.10620939e-07, -1.39567495e-07,  3.00000088e+00,  0.00000000e+00,
        0.00000000e+00])

In [50]:
X[:,0:3]

array([[ 1.00000009e+00,  2.08017562e-07, -2.10620939e-07],
       [ 0.00000000e+00,  1.99999837e+00, -1.39567495e-07],
       [ 0.00000000e+00,  0.00000000e+00,  3.00000088e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [16]:
np.mean(ts)

6.733710694313049

In [63]:
theta

array([  1.        ,   1.99999987,   3.0000014 ,   4.00000026,
         5.00000013,   5.99999934,   7.00000137,   8.00000094,
         8.99999909, 470.83363624, 486.77957389, 495.88967838,
       502.21886489, 518.87077446, 526.27381392, 540.54502216,
       556.40414906])

In [58]:
theta[:eig]

array([1.        , 1.99999987, 3.0000014 , 4.00000026])

In [59]:
e,v = np.linalg.eig(A)

In [61]:
e[0] - theta[:eig][0]

1.7774670624248756e-13